FROM alpine:latest

ENV SERVER_LISTEN_ADDRESS '0.0.0.0'
ENV SERVER_LISTEN_PORT '80'
ENV GRPC_SERVER_LISTEN_ADDRESS '0.0.0.0'
ENV GRPC_SERVER_LISTEN_PORT '9999'
ENV SERVICE_NAME_AS_ROOT 'false'

ENV DATABASE_DIALECT 'mysql'
ENV DATABASE_USERNAME 'root'
ENV DATABASE_PASSWORD 'root'
ENV DATABASE_HOST 'mysql-service'
ENV DATABASE_PORT '3306'
ENV DATABASE_NAME 'be-member'

ENV REDIS_ENDPOINT 'redis-service:6379'
ENV REDIS_DB '0'
ENV REDIS_POOLSIZE '100'
ENV REDIS_IDLE_TIMEOUT '60000'
ENV REDIS_MAX_IDLE_CONNECTIONS '10'
ENV REDIS_CONNECTION_IDLE_TIMEOUT_MS '60000'
ENV REDIS_PASSWORD '123456'

ENV SERVICE_NAME 'be-member'
ENV SERVER_ENV 'dev'
ENV LOG_LEVEL '4'
ENV STACKDRIVER_ENABLED 'false'
ENV GRPC_CONNECT_TIMEOUT_MS '15000'
ENV PROJECT_ID 'paper-trade-chatbot'
ENV FCM_KEY '.'
ENV CDN_URL_PREFIX "https://storage.googleapis.com"
ENV SERVER_SHUTDOWN_GRACE_PERIOD_MS '30000'
ENV GCS_BUCKET_NAME 'paper-trade-chatbot-bucket'
ENV WALLET_GRPC_HOST 'rf-wallet'
ENV WALLET_GRPC_PORT '9999'
ENV MEMBER_GRPC_HOST 'rf-member'
ENV MEMBER_GRPC_PORT '9999'
ENV AUTH_GRPC_HOST 'rf-auth'
ENV AUTH_GRPC_PORT '9999'
ENV DISTRIBUTION_GRPC_HOST 'rf-distribution'
ENV DISTRIBUTION_GRPC_PORT '9999'
ENV LOG_GRPC_HOST 'rf-log'
ENV LOG_GRPC_PORT '9999'
ENV ORDER_GRPC_HOST 'rf-order'
ENV ORDER_GRPC_PORT '9999'
ENV PRODUCT_GRPC_HOST "rf-product"
ENV PRODUCT_GRPC_PORT '9999'
ENV LIVE_GRPC_HOST "rf-live"
ENV LIVE_GRPC_PORT "9999"
ENV PROMOTION_GRPC_HOST "rf-promotion"
ENV PROMOTION_GRPC_PORT "9999"
ENV PAYMENT_GRPC_PORT "9999"
ENV PAYMENT_GRPC_HOST "rf-payment"
ENV MEDIA_GRPC_HOST "rf-media"
ENV MEDIA_GRPC_PORT "9999"
ENV WAREHOUSE_GRPC_HOST "rf-warehouse"
ENV WAREHOUSE_GRPC_PORT "9999"
ENV QUOTE_GRPC_HOST "rf-quote"
ENV QUOTE_GRPC_PORT "9999"
ENV RISK_GRPC_PORT "9999"
ENV RISK_GRPC_HOST "rf-risk"
ENV REPLAY_GRPC_PORT "9999"
ENV REPLAY_GRPC_HOST "rf-replay"

ENV SOURCE_GRPC_HOST "rf-source"
ENV SOURCE_GRPC_PORT "50051"

RUN apk add --update-cache tzdata
COPY be-member /be-member

ENTRYPOINT ["/be-member"]


