package databaseModels

const (
	OPENCLOSE_OPEN         = 1
	OPENCLOSE_CLOSE        = 2
	SIDE_BUY               = 1
	SIDE_SELL              = 2
	ORDER_STATUS_UNSETTLED = 1
	ORDER_STATUS_SETTLED   = 2
	ORDER_STATUS_FAILED    = 3
	ORDER_STATUS_MODIFY    = 4
	ORDER_STATUS_CANCELED  = 5

	ORDER_ACTION_NEW    = 1
	ORDER_ACTION_CANCEL = 2
	ORDER_ACTION_MODIFY = 3
	WALLET_LEVERAGE     = "2"
)
